// Author: Sean Pesce
/*
	d3dx9_43.h

	Defines the jumps to all functions exported by the d3dx9_43.dll shared library.
*/


#pragma once


#ifndef _SP_DS1_FPS_FIX_PLUS_D3DX9_43_H_
	#define _SP_DS1_FPS_FIX_PLUS_D3DX9_43_H_


#ifdef _SP_WRAP_D3DX9_43_DLL_


#define _SP_WRAPPED_LIB_ "d3dx9_43"
#define _SP_EXPORT_COUNT_ 329
UINT_PTR mProcs[_SP_EXPORT_COUNT_] = { 0 };
LPCSTR mImportNames[] = {"D3DXAssembleShader", "D3DXAssembleShaderFromFileA", "D3DXAssembleShaderFromFileW", "D3DXAssembleShaderFromResourceA", "D3DXAssembleShaderFromResourceW", "D3DXBoxBoundProbe", "D3DXCheckCubeTextureRequirements", "D3DXCheckTextureRequirements", "D3DXCheckVersion", "D3DXCheckVolumeTextureRequirements", "D3DXCleanMesh", "D3DXColorAdjustContrast", "D3DXColorAdjustSaturation", "D3DXCompileShader", "D3DXCompileShaderFromFileA", "D3DXCompileShaderFromFileW", "D3DXCompileShaderFromResourceA", "D3DXCompileShaderFromResourceW", "D3DXComputeBoundingBox", "D3DXComputeBoundingSphere", "D3DXComputeIMTFromPerTexelSignal", "D3DXComputeIMTFromPerVertexSignal", "D3DXComputeIMTFromSignal", "D3DXComputeIMTFromTexture", "D3DXComputeNormalMap", "D3DXComputeNormals", "D3DXComputeTangent", "D3DXComputeTangentFrame", "D3DXComputeTangentFrameEx", "D3DXConcatenateMeshes", "D3DXConvertMeshSubsetToSingleStrip", "D3DXConvertMeshSubsetToStrips", "D3DXCreateAnimationController", "D3DXCreateBox", "D3DXCreateBuffer", "D3DXCreateCompressedAnimationSet", "D3DXCreateCubeTexture", "D3DXCreateCubeTextureFromFileA", "D3DXCreateCubeTextureFromFileExA", "D3DXCreateCubeTextureFromFileExW", "D3DXCreateCubeTextureFromFileInMemory", "D3DXCreateCubeTextureFromFileInMemoryEx", "D3DXCreateCubeTextureFromFileW", "D3DXCreateCubeTextureFromResourceA", "D3DXCreateCubeTextureFromResourceExA", "D3DXCreateCubeTextureFromResourceExW", "D3DXCreateCubeTextureFromResourceW", "D3DXCreateCylinder", "D3DXCreateEffect", "D3DXCreateEffectCompiler", "D3DXCreateEffectCompilerFromFileA", "D3DXCreateEffectCompilerFromFileW", "D3DXCreateEffectCompilerFromResourceA", "D3DXCreateEffectCompilerFromResourceW", "D3DXCreateEffectEx", "D3DXCreateEffectFromFileA", "D3DXCreateEffectFromFileExA", "D3DXCreateEffectFromFileExW", "D3DXCreateEffectFromFileW", "D3DXCreateEffectFromResourceA", "D3DXCreateEffectFromResourceExA", "D3DXCreateEffectFromResourceExW", "D3DXCreateEffectFromResourceW", "D3DXCreateEffectPool", "D3DXCreateFontA", "D3DXCreateFontIndirectA", "D3DXCreateFontIndirectW", "D3DXCreateFontW", "D3DXCreateKeyframedAnimationSet", "D3DXCreateLine", "D3DXCreateMatrixStack", "D3DXCreateMesh", "D3DXCreateMeshFVF", "D3DXCreateNPatchMesh", "D3DXCreatePMeshFromStream", "D3DXCreatePRTBuffer", "D3DXCreatePRTBufferTex", "D3DXCreatePRTCompBuffer", "D3DXCreatePRTEngine", "D3DXCreatePatchMesh", "D3DXCreatePolygon", "D3DXCreateRenderToEnvMap", "D3DXCreateRenderToSurface", "D3DXCreateSPMesh", "D3DXCreateSkinInfo", "D3DXCreateSkinInfoFVF", "D3DXCreateSkinInfoFromBlendedMesh", "D3DXCreateSphere", "D3DXCreateSprite", "D3DXCreateTeapot", "D3DXCreateTextA", "D3DXCreateTextW", "D3DXCreateTexture", "D3DXCreateTextureFromFileA", "D3DXCreateTextureFromFileExA", "D3DXCreateTextureFromFileExW", "D3DXCreateTextureFromFileInMemory", "D3DXCreateTextureFromFileInMemoryEx", "D3DXCreateTextureFromFileW", "D3DXCreateTextureFromResourceA", "D3DXCreateTextureFromResourceExA", "D3DXCreateTextureFromResourceExW", "D3DXCreateTextureFromResourceW", "D3DXCreateTextureGutterHelper", "D3DXCreateTextureShader", "D3DXCreateTorus", "D3DXCreateVolumeTexture", "D3DXCreateVolumeTextureFromFileA", "D3DXCreateVolumeTextureFromFileExA", "D3DXCreateVolumeTextureFromFileExW", "D3DXCreateVolumeTextureFromFileInMemory", "D3DXCreateVolumeTextureFromFileInMemoryEx", "D3DXCreateVolumeTextureFromFileW", "D3DXCreateVolumeTextureFromResourceA", "D3DXCreateVolumeTextureFromResourceExA", "D3DXCreateVolumeTextureFromResourceExW", "D3DXCreateVolumeTextureFromResourceW", "D3DXDebugMute", "D3DXDeclaratorFromFVF", "D3DXDisassembleEffect", "D3DXDisassembleShader", "D3DXFVFFromDeclarator", "D3DXFileCreate", "D3DXFillCubeTexture", "D3DXFillCubeTextureTX", "D3DXFillTexture", "D3DXFillTextureTX", "D3DXFillVolumeTexture", "D3DXFillVolumeTextureTX", "D3DXFilterTexture", "D3DXFindShaderComment", "D3DXFloat16To32Array", "D3DXFloat32To16Array", "D3DXFrameAppendChild", "D3DXFrameCalculateBoundingSphere", "D3DXFrameDestroy", "D3DXFrameFind", "D3DXFrameNumNamedMatrices", "D3DXFrameRegisterNamedMatrices", "D3DXFresnelTerm", "D3DXGenerateOutputDecl", "D3DXGeneratePMesh", "D3DXGetDeclLength", "D3DXGetDeclVertexSize", "D3DXGetDriverLevel", "D3DXGetFVFVertexSize", "D3DXGetImageInfoFromFileA", "D3DXGetImageInfoFromFileInMemory", "D3DXGetImageInfoFromFileW", "D3DXGetImageInfoFromResourceA", "D3DXGetImageInfoFromResourceW", "D3DXGetPixelShaderProfile", "D3DXGetShaderConstantTable", "D3DXGetShaderConstantTableEx", "D3DXGetShaderInputSemantics", "D3DXGetShaderOutputSemantics", "D3DXGetShaderSamplers", "D3DXGetShaderSize", "D3DXGetShaderVersion", "D3DXGetVertexShaderProfile", "D3DXIntersect", "D3DXIntersectSubset", "D3DXIntersectTri", "D3DXLoadMeshFromXA", "D3DXLoadMeshFromXInMemory", "D3DXLoadMeshFromXResource", "D3DXLoadMeshFromXW", "D3DXLoadMeshFromXof", "D3DXLoadMeshHierarchyFromXA", "D3DXLoadMeshHierarchyFromXInMemory", "D3DXLoadMeshHierarchyFromXW", "D3DXLoadPRTBufferFromFileA", "D3DXLoadPRTBufferFromFileW", "D3DXLoadPRTCompBufferFromFileA", "D3DXLoadPRTCompBufferFromFileW", "D3DXLoadPatchMeshFromXof", "D3DXLoadSkinMeshFromXof", "D3DXLoadSurfaceFromFileA", "D3DXLoadSurfaceFromFileInMemory", "D3DXLoadSurfaceFromFileW", "D3DXLoadSurfaceFromMemory", "D3DXLoadSurfaceFromResourceA", "D3DXLoadSurfaceFromResourceW", "D3DXLoadSurfaceFromSurface", "D3DXLoadVolumeFromFileA", "D3DXLoadVolumeFromFileInMemory", "D3DXLoadVolumeFromFileW", "D3DXLoadVolumeFromMemory", "D3DXLoadVolumeFromResourceA", "D3DXLoadVolumeFromResourceW", "D3DXLoadVolumeFromVolume", "D3DXMatrixAffineTransformation", "D3DXMatrixAffineTransformation2D", "D3DXMatrixDecompose", "D3DXMatrixDeterminant", "D3DXMatrixInverse", "D3DXMatrixLookAtLH", "D3DXMatrixLookAtRH", "D3DXMatrixMultiply", "D3DXMatrixMultiplyTranspose", "D3DXMatrixOrthoLH", "D3DXMatrixOrthoOffCenterLH", "D3DXMatrixOrthoOffCenterRH", "D3DXMatrixOrthoRH", "D3DXMatrixPerspectiveFovLH", "D3DXMatrixPerspectiveFovRH", "D3DXMatrixPerspectiveLH", "D3DXMatrixPerspectiveOffCenterLH", "D3DXMatrixPerspectiveOffCenterRH", "D3DXMatrixPerspectiveRH", "D3DXMatrixReflect", "D3DXMatrixRotationAxis", "D3DXMatrixRotationQuaternion", "D3DXMatrixRotationX", "D3DXMatrixRotationY", "D3DXMatrixRotationYawPitchRoll", "D3DXMatrixRotationZ", "D3DXMatrixScaling", "D3DXMatrixShadow", "D3DXMatrixTransformation", "D3DXMatrixTransformation2D", "D3DXMatrixTranslation", "D3DXMatrixTranspose", "D3DXOptimizeFaces", "D3DXOptimizeVertices", "D3DXPlaneFromPointNormal", "D3DXPlaneFromPoints", "D3DXPlaneIntersectLine", "D3DXPlaneNormalize", "D3DXPlaneTransform", "D3DXPlaneTransformArray", "D3DXPreprocessShader", "D3DXPreprocessShaderFromFileA", "D3DXPreprocessShaderFromFileW", "D3DXPreprocessShaderFromResourceA", "D3DXPreprocessShaderFromResourceW", "D3DXQuaternionBaryCentric", "D3DXQuaternionExp", "D3DXQuaternionInverse", "D3DXQuaternionLn", "D3DXQuaternionMultiply", "D3DXQuaternionNormalize", "D3DXQuaternionRotationAxis", "D3DXQuaternionRotationMatrix", "D3DXQuaternionRotationYawPitchRoll", "D3DXQuaternionSlerp", "D3DXQuaternionSquad", "D3DXQuaternionSquadSetup", "D3DXQuaternionToAxisAngle", "D3DXRectPatchSize", "D3DXSHAdd", "D3DXSHDot", "D3DXSHEvalConeLight", "D3DXSHEvalDirection", "D3DXSHEvalDirectionalLight", "D3DXSHEvalHemisphereLight", "D3DXSHEvalSphericalLight", "D3DXSHMultiply2", "D3DXSHMultiply3", "D3DXSHMultiply4", "D3DXSHMultiply5", "D3DXSHMultiply6", "D3DXSHPRTCompSplitMeshSC", "D3DXSHPRTCompSuperCluster", "D3DXSHProjectCubeMap", "D3DXSHRotate", "D3DXSHRotateZ", "D3DXSHScale", "D3DXSaveMeshHierarchyToFileA", "D3DXSaveMeshHierarchyToFileW", "D3DXSaveMeshToXA", "D3DXSaveMeshToXW", "D3DXSavePRTBufferToFileA", "D3DXSavePRTBufferToFileW", "D3DXSavePRTCompBufferToFileA", "D3DXSavePRTCompBufferToFileW", "D3DXSaveSurfaceToFileA", "D3DXSaveSurfaceToFileInMemory", "D3DXSaveSurfaceToFileW", "D3DXSaveTextureToFileA", "D3DXSaveTextureToFileInMemory", "D3DXSaveTextureToFileW", "D3DXSaveVolumeToFileA", "D3DXSaveVolumeToFileInMemory", "D3DXSaveVolumeToFileW", "D3DXSimplifyMesh", "D3DXSphereBoundProbe", "D3DXSplitMesh", "D3DXTessellateNPatches", "D3DXTessellateRectPatch", "D3DXTessellateTriPatch", "D3DXTriPatchSize", "D3DXUVAtlasCreate", "D3DXUVAtlasPack", "D3DXUVAtlasPartition", "D3DXValidMesh", "D3DXValidPatchMesh", "D3DXVec2BaryCentric", "D3DXVec2CatmullRom", "D3DXVec2Hermite", "D3DXVec2Normalize", "D3DXVec2Transform", "D3DXVec2TransformArray", "D3DXVec2TransformCoord", "D3DXVec2TransformCoordArray", "D3DXVec2TransformNormal", "D3DXVec2TransformNormalArray", "D3DXVec3BaryCentric", "D3DXVec3CatmullRom", "D3DXVec3Hermite", "D3DXVec3Normalize", "D3DXVec3Project", "D3DXVec3ProjectArray", "D3DXVec3Transform", "D3DXVec3TransformArray", "D3DXVec3TransformCoord", "D3DXVec3TransformCoordArray", "D3DXVec3TransformNormal", "D3DXVec3TransformNormalArray", "D3DXVec3Unproject", "D3DXVec3UnprojectArray", "D3DXVec4BaryCentric", "D3DXVec4CatmullRom", "D3DXVec4Cross", "D3DXVec4Hermite", "D3DXVec4Normalize", "D3DXVec4Transform", "D3DXVec4TransformArray", "D3DXWeldVertices"};

extern "C" __declspec(naked) void __stdcall D3DXAssembleShader_wrapper(){__asm{jmp mProcs[0*4]}}
extern "C" __declspec(naked) void __stdcall D3DXAssembleShaderFromFileA_wrapper(){__asm{jmp mProcs[1*4]}}
extern "C" __declspec(naked) void __stdcall D3DXAssembleShaderFromFileW_wrapper(){__asm{jmp mProcs[2*4]}}
extern "C" __declspec(naked) void __stdcall D3DXAssembleShaderFromResourceA_wrapper(){__asm{jmp mProcs[3*4]}}
extern "C" __declspec(naked) void __stdcall D3DXAssembleShaderFromResourceW_wrapper(){__asm{jmp mProcs[4*4]}}
extern "C" __declspec(naked) void __stdcall D3DXBoxBoundProbe_wrapper(){__asm{jmp mProcs[5*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCheckCubeTextureRequirements_wrapper(){__asm{jmp mProcs[6*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCheckTextureRequirements_wrapper(){__asm{jmp mProcs[7*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCheckVersion_wrapper(){__asm{jmp mProcs[8*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCheckVolumeTextureRequirements_wrapper(){__asm{jmp mProcs[9*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCleanMesh_wrapper(){__asm{jmp mProcs[10*4]}}
extern "C" __declspec(naked) void __stdcall D3DXColorAdjustContrast_wrapper(){__asm{jmp mProcs[11*4]}}
extern "C" __declspec(naked) void __stdcall D3DXColorAdjustSaturation_wrapper(){__asm{jmp mProcs[12*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCompileShader_wrapper(){__asm{jmp mProcs[13*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCompileShaderFromFileA_wrapper(){__asm{jmp mProcs[14*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCompileShaderFromFileW_wrapper(){__asm{jmp mProcs[15*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCompileShaderFromResourceA_wrapper(){__asm{jmp mProcs[16*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCompileShaderFromResourceW_wrapper(){__asm{jmp mProcs[17*4]}}
extern "C" __declspec(naked) void __stdcall D3DXComputeBoundingBox_wrapper(){__asm{jmp mProcs[18*4]}}
extern "C" __declspec(naked) void __stdcall D3DXComputeBoundingSphere_wrapper(){__asm{jmp mProcs[19*4]}}
extern "C" __declspec(naked) void __stdcall D3DXComputeIMTFromPerTexelSignal_wrapper(){__asm{jmp mProcs[20*4]}}
extern "C" __declspec(naked) void __stdcall D3DXComputeIMTFromPerVertexSignal_wrapper(){__asm{jmp mProcs[21*4]}}
extern "C" __declspec(naked) void __stdcall D3DXComputeIMTFromSignal_wrapper(){__asm{jmp mProcs[22*4]}}
extern "C" __declspec(naked) void __stdcall D3DXComputeIMTFromTexture_wrapper(){__asm{jmp mProcs[23*4]}}
extern "C" __declspec(naked) void __stdcall D3DXComputeNormalMap_wrapper(){__asm{jmp mProcs[24*4]}}
extern "C" __declspec(naked) void __stdcall D3DXComputeNormals_wrapper(){__asm{jmp mProcs[25*4]}}
extern "C" __declspec(naked) void __stdcall D3DXComputeTangent_wrapper(){__asm{jmp mProcs[26*4]}}
extern "C" __declspec(naked) void __stdcall D3DXComputeTangentFrame_wrapper(){__asm{jmp mProcs[27*4]}}
extern "C" __declspec(naked) void __stdcall D3DXComputeTangentFrameEx_wrapper(){__asm{jmp mProcs[28*4]}}
extern "C" __declspec(naked) void __stdcall D3DXConcatenateMeshes_wrapper(){__asm{jmp mProcs[29*4]}}
extern "C" __declspec(naked) void __stdcall D3DXConvertMeshSubsetToSingleStrip_wrapper(){__asm{jmp mProcs[30*4]}}
extern "C" __declspec(naked) void __stdcall D3DXConvertMeshSubsetToStrips_wrapper(){__asm{jmp mProcs[31*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateAnimationController_wrapper(){__asm{jmp mProcs[32*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateBox_wrapper(){__asm{jmp mProcs[33*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateBuffer_wrapper(){__asm{jmp mProcs[34*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateCompressedAnimationSet_wrapper(){__asm{jmp mProcs[35*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateCubeTexture_wrapper(){__asm{jmp mProcs[36*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateCubeTextureFromFileA_wrapper(){__asm{jmp mProcs[37*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateCubeTextureFromFileExA_wrapper(){__asm{jmp mProcs[38*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateCubeTextureFromFileExW_wrapper(){__asm{jmp mProcs[39*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateCubeTextureFromFileInMemory_wrapper(){__asm{jmp mProcs[40*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateCubeTextureFromFileInMemoryEx_wrapper(){__asm{jmp mProcs[41*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateCubeTextureFromFileW_wrapper(){__asm{jmp mProcs[42*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateCubeTextureFromResourceA_wrapper(){__asm{jmp mProcs[43*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateCubeTextureFromResourceExA_wrapper(){__asm{jmp mProcs[44*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateCubeTextureFromResourceExW_wrapper(){__asm{jmp mProcs[45*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateCubeTextureFromResourceW_wrapper(){__asm{jmp mProcs[46*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateCylinder_wrapper(){__asm{jmp mProcs[47*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateEffect_wrapper(){__asm{jmp mProcs[48*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateEffectCompiler_wrapper(){__asm{jmp mProcs[49*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateEffectCompilerFromFileA_wrapper(){__asm{jmp mProcs[50*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateEffectCompilerFromFileW_wrapper(){__asm{jmp mProcs[51*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateEffectCompilerFromResourceA_wrapper(){__asm{jmp mProcs[52*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateEffectCompilerFromResourceW_wrapper(){__asm{jmp mProcs[53*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateEffectEx_wrapper(){__asm{jmp mProcs[54*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateEffectFromFileA_wrapper(){__asm{jmp mProcs[55*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateEffectFromFileExA_wrapper(){__asm{jmp mProcs[56*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateEffectFromFileExW_wrapper(){__asm{jmp mProcs[57*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateEffectFromFileW_wrapper(){__asm{jmp mProcs[58*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateEffectFromResourceA_wrapper(){__asm{jmp mProcs[59*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateEffectFromResourceExA_wrapper(){__asm{jmp mProcs[60*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateEffectFromResourceExW_wrapper(){__asm{jmp mProcs[61*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateEffectFromResourceW_wrapper(){__asm{jmp mProcs[62*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateEffectPool_wrapper(){__asm{jmp mProcs[63*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateFontA_wrapper(){__asm{jmp mProcs[64*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateFontIndirectA_wrapper(){__asm{jmp mProcs[65*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateFontIndirectW_wrapper(){__asm{jmp mProcs[66*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateFontW_wrapper(){__asm{jmp mProcs[67*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateKeyframedAnimationSet_wrapper(){__asm{jmp mProcs[68*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateLine_wrapper(){__asm{jmp mProcs[69*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateMatrixStack_wrapper(){__asm{jmp mProcs[70*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateMesh_wrapper(){__asm{jmp mProcs[71*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateMeshFVF_wrapper(){__asm{jmp mProcs[72*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateNPatchMesh_wrapper(){__asm{jmp mProcs[73*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreatePMeshFromStream_wrapper(){__asm{jmp mProcs[74*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreatePRTBuffer_wrapper(){__asm{jmp mProcs[75*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreatePRTBufferTex_wrapper(){__asm{jmp mProcs[76*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreatePRTCompBuffer_wrapper(){__asm{jmp mProcs[77*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreatePRTEngine_wrapper(){__asm{jmp mProcs[78*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreatePatchMesh_wrapper(){__asm{jmp mProcs[79*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreatePolygon_wrapper(){__asm{jmp mProcs[80*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateRenderToEnvMap_wrapper(){__asm{jmp mProcs[81*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateRenderToSurface_wrapper(){__asm{jmp mProcs[82*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateSPMesh_wrapper(){__asm{jmp mProcs[83*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateSkinInfo_wrapper(){__asm{jmp mProcs[84*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateSkinInfoFVF_wrapper(){__asm{jmp mProcs[85*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateSkinInfoFromBlendedMesh_wrapper(){__asm{jmp mProcs[86*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateSphere_wrapper(){__asm{jmp mProcs[87*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateSprite_wrapper(){__asm{jmp mProcs[88*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateTeapot_wrapper(){__asm{jmp mProcs[89*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateTextA_wrapper(){__asm{jmp mProcs[90*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateTextW_wrapper(){__asm{jmp mProcs[91*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateTexture_wrapper(){__asm{jmp mProcs[92*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateTextureFromFileA_wrapper(){__asm{jmp mProcs[93*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateTextureFromFileExA_wrapper(){__asm{jmp mProcs[94*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateTextureFromFileExW_wrapper(){__asm{jmp mProcs[95*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateTextureFromFileInMemory_wrapper(){__asm{jmp mProcs[96*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateTextureFromFileInMemoryEx_wrapper(){__asm{jmp mProcs[97*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateTextureFromFileW_wrapper(){__asm{jmp mProcs[98*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateTextureFromResourceA_wrapper(){__asm{jmp mProcs[99*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateTextureFromResourceExA_wrapper(){__asm{jmp mProcs[100*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateTextureFromResourceExW_wrapper(){__asm{jmp mProcs[101*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateTextureFromResourceW_wrapper(){__asm{jmp mProcs[102*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateTextureGutterHelper_wrapper(){__asm{jmp mProcs[103*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateTextureShader_wrapper(){__asm{jmp mProcs[104*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateTorus_wrapper(){__asm{jmp mProcs[105*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateVolumeTexture_wrapper(){__asm{jmp mProcs[106*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateVolumeTextureFromFileA_wrapper(){__asm{jmp mProcs[107*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateVolumeTextureFromFileExA_wrapper(){__asm{jmp mProcs[108*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateVolumeTextureFromFileExW_wrapper(){__asm{jmp mProcs[109*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateVolumeTextureFromFileInMemory_wrapper(){__asm{jmp mProcs[110*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateVolumeTextureFromFileInMemoryEx_wrapper(){__asm{jmp mProcs[111*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateVolumeTextureFromFileW_wrapper(){__asm{jmp mProcs[112*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateVolumeTextureFromResourceA_wrapper(){__asm{jmp mProcs[113*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateVolumeTextureFromResourceExA_wrapper(){__asm{jmp mProcs[114*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateVolumeTextureFromResourceExW_wrapper(){__asm{jmp mProcs[115*4]}}
extern "C" __declspec(naked) void __stdcall D3DXCreateVolumeTextureFromResourceW_wrapper(){__asm{jmp mProcs[116*4]}}
extern "C" __declspec(naked) void __stdcall D3DXDebugMute_wrapper(){__asm{jmp mProcs[117*4]}}
extern "C" __declspec(naked) void __stdcall D3DXDeclaratorFromFVF_wrapper(){__asm{jmp mProcs[118*4]}}
extern "C" __declspec(naked) void __stdcall D3DXDisassembleEffect_wrapper(){__asm{jmp mProcs[119*4]}}
extern "C" __declspec(naked) void __stdcall D3DXDisassembleShader_wrapper(){__asm{jmp mProcs[120*4]}}
extern "C" __declspec(naked) void __stdcall D3DXFVFFromDeclarator_wrapper(){__asm{jmp mProcs[121*4]}}
extern "C" __declspec(naked) void __stdcall D3DXFileCreate_wrapper(){__asm{jmp mProcs[122*4]}}
extern "C" __declspec(naked) void __stdcall D3DXFillCubeTexture_wrapper(){__asm{jmp mProcs[123*4]}}
extern "C" __declspec(naked) void __stdcall D3DXFillCubeTextureTX_wrapper(){__asm{jmp mProcs[124*4]}}
extern "C" __declspec(naked) void __stdcall D3DXFillTexture_wrapper(){__asm{jmp mProcs[125*4]}}
extern "C" __declspec(naked) void __stdcall D3DXFillTextureTX_wrapper(){__asm{jmp mProcs[126*4]}}
extern "C" __declspec(naked) void __stdcall D3DXFillVolumeTexture_wrapper(){__asm{jmp mProcs[127*4]}}
extern "C" __declspec(naked) void __stdcall D3DXFillVolumeTextureTX_wrapper(){__asm{jmp mProcs[128*4]}}
extern "C" __declspec(naked) void __stdcall D3DXFilterTexture_wrapper(){__asm{jmp mProcs[129*4]}}
extern "C" __declspec(naked) void __stdcall D3DXFindShaderComment_wrapper(){__asm{jmp mProcs[130*4]}}
extern "C" __declspec(naked) void __stdcall D3DXFloat16To32Array_wrapper(){__asm{jmp mProcs[131*4]}}
extern "C" __declspec(naked) void __stdcall D3DXFloat32To16Array_wrapper(){__asm{jmp mProcs[132*4]}}
extern "C" __declspec(naked) void __stdcall D3DXFrameAppendChild_wrapper(){__asm{jmp mProcs[133*4]}}
extern "C" __declspec(naked) void __stdcall D3DXFrameCalculateBoundingSphere_wrapper(){__asm{jmp mProcs[134*4]}}
extern "C" __declspec(naked) void __stdcall D3DXFrameDestroy_wrapper(){__asm{jmp mProcs[135*4]}}
extern "C" __declspec(naked) void __stdcall D3DXFrameFind_wrapper(){__asm{jmp mProcs[136*4]}}
extern "C" __declspec(naked) void __stdcall D3DXFrameNumNamedMatrices_wrapper(){__asm{jmp mProcs[137*4]}}
extern "C" __declspec(naked) void __stdcall D3DXFrameRegisterNamedMatrices_wrapper(){__asm{jmp mProcs[138*4]}}
extern "C" __declspec(naked) void __stdcall D3DXFresnelTerm_wrapper(){__asm{jmp mProcs[139*4]}}
extern "C" __declspec(naked) void __stdcall D3DXGenerateOutputDecl_wrapper(){__asm{jmp mProcs[140*4]}}
extern "C" __declspec(naked) void __stdcall D3DXGeneratePMesh_wrapper(){__asm{jmp mProcs[141*4]}}
extern "C" __declspec(naked) void __stdcall D3DXGetDeclLength_wrapper(){__asm{jmp mProcs[142*4]}}
extern "C" __declspec(naked) void __stdcall D3DXGetDeclVertexSize_wrapper(){__asm{jmp mProcs[143*4]}}
extern "C" __declspec(naked) void __stdcall D3DXGetDriverLevel_wrapper(){__asm{jmp mProcs[144*4]}}
extern "C" __declspec(naked) void __stdcall D3DXGetFVFVertexSize_wrapper(){__asm{jmp mProcs[145*4]}}
extern "C" __declspec(naked) void __stdcall D3DXGetImageInfoFromFileA_wrapper(){__asm{jmp mProcs[146*4]}}
extern "C" __declspec(naked) void __stdcall D3DXGetImageInfoFromFileInMemory_wrapper(){__asm{jmp mProcs[147*4]}}
extern "C" __declspec(naked) void __stdcall D3DXGetImageInfoFromFileW_wrapper(){__asm{jmp mProcs[148*4]}}
extern "C" __declspec(naked) void __stdcall D3DXGetImageInfoFromResourceA_wrapper(){__asm{jmp mProcs[149*4]}}
extern "C" __declspec(naked) void __stdcall D3DXGetImageInfoFromResourceW_wrapper(){__asm{jmp mProcs[150*4]}}
extern "C" __declspec(naked) void __stdcall D3DXGetPixelShaderProfile_wrapper(){__asm{jmp mProcs[151*4]}}
extern "C" __declspec(naked) void __stdcall D3DXGetShaderConstantTable_wrapper(){__asm{jmp mProcs[152*4]}}
extern "C" __declspec(naked) void __stdcall D3DXGetShaderConstantTableEx_wrapper(){__asm{jmp mProcs[153*4]}}
extern "C" __declspec(naked) void __stdcall D3DXGetShaderInputSemantics_wrapper(){__asm{jmp mProcs[154*4]}}
extern "C" __declspec(naked) void __stdcall D3DXGetShaderOutputSemantics_wrapper(){__asm{jmp mProcs[155*4]}}
extern "C" __declspec(naked) void __stdcall D3DXGetShaderSamplers_wrapper(){__asm{jmp mProcs[156*4]}}
extern "C" __declspec(naked) void __stdcall D3DXGetShaderSize_wrapper(){__asm{jmp mProcs[157*4]}}
extern "C" __declspec(naked) void __stdcall D3DXGetShaderVersion_wrapper(){__asm{jmp mProcs[158*4]}}
extern "C" __declspec(naked) void __stdcall D3DXGetVertexShaderProfile_wrapper(){__asm{jmp mProcs[159*4]}}
extern "C" __declspec(naked) void __stdcall D3DXIntersect_wrapper(){__asm{jmp mProcs[160*4]}}
extern "C" __declspec(naked) void __stdcall D3DXIntersectSubset_wrapper(){__asm{jmp mProcs[161*4]}}
extern "C" __declspec(naked) void __stdcall D3DXIntersectTri_wrapper(){__asm{jmp mProcs[162*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadMeshFromXA_wrapper(){__asm{jmp mProcs[163*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadMeshFromXInMemory_wrapper(){__asm{jmp mProcs[164*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadMeshFromXResource_wrapper(){__asm{jmp mProcs[165*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadMeshFromXW_wrapper(){__asm{jmp mProcs[166*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadMeshFromXof_wrapper(){__asm{jmp mProcs[167*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadMeshHierarchyFromXA_wrapper(){__asm{jmp mProcs[168*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadMeshHierarchyFromXInMemory_wrapper(){__asm{jmp mProcs[169*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadMeshHierarchyFromXW_wrapper(){__asm{jmp mProcs[170*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadPRTBufferFromFileA_wrapper(){__asm{jmp mProcs[171*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadPRTBufferFromFileW_wrapper(){__asm{jmp mProcs[172*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadPRTCompBufferFromFileA_wrapper(){__asm{jmp mProcs[173*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadPRTCompBufferFromFileW_wrapper(){__asm{jmp mProcs[174*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadPatchMeshFromXof_wrapper(){__asm{jmp mProcs[175*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadSkinMeshFromXof_wrapper(){__asm{jmp mProcs[176*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadSurfaceFromFileA_wrapper(){__asm{jmp mProcs[177*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadSurfaceFromFileInMemory_wrapper(){__asm{jmp mProcs[178*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadSurfaceFromFileW_wrapper(){__asm{jmp mProcs[179*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadSurfaceFromMemory_wrapper(){__asm{jmp mProcs[180*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadSurfaceFromResourceA_wrapper(){__asm{jmp mProcs[181*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadSurfaceFromResourceW_wrapper(){__asm{jmp mProcs[182*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadSurfaceFromSurface_wrapper(){__asm{jmp mProcs[183*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadVolumeFromFileA_wrapper(){__asm{jmp mProcs[184*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadVolumeFromFileInMemory_wrapper(){__asm{jmp mProcs[185*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadVolumeFromFileW_wrapper(){__asm{jmp mProcs[186*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadVolumeFromMemory_wrapper(){__asm{jmp mProcs[187*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadVolumeFromResourceA_wrapper(){__asm{jmp mProcs[188*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadVolumeFromResourceW_wrapper(){__asm{jmp mProcs[189*4]}}
extern "C" __declspec(naked) void __stdcall D3DXLoadVolumeFromVolume_wrapper(){__asm{jmp mProcs[190*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixAffineTransformation_wrapper(){__asm{jmp mProcs[191*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixAffineTransformation2D_wrapper(){__asm{jmp mProcs[192*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixDecompose_wrapper(){__asm{jmp mProcs[193*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixDeterminant_wrapper(){__asm{jmp mProcs[194*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixInverse_wrapper(){__asm{jmp mProcs[195*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixLookAtLH_wrapper(){__asm{jmp mProcs[196*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixLookAtRH_wrapper(){__asm{jmp mProcs[197*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixMultiply_wrapper(){__asm{jmp mProcs[198*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixMultiplyTranspose_wrapper(){__asm{jmp mProcs[199*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixOrthoLH_wrapper(){__asm{jmp mProcs[200*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixOrthoOffCenterLH_wrapper(){__asm{jmp mProcs[201*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixOrthoOffCenterRH_wrapper(){__asm{jmp mProcs[202*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixOrthoRH_wrapper(){__asm{jmp mProcs[203*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixPerspectiveFovLH_wrapper(){__asm{jmp mProcs[204*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixPerspectiveFovRH_wrapper(){__asm{jmp mProcs[205*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixPerspectiveLH_wrapper(){__asm{jmp mProcs[206*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixPerspectiveOffCenterLH_wrapper(){__asm{jmp mProcs[207*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixPerspectiveOffCenterRH_wrapper(){__asm{jmp mProcs[208*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixPerspectiveRH_wrapper(){__asm{jmp mProcs[209*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixReflect_wrapper(){__asm{jmp mProcs[210*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixRotationAxis_wrapper(){__asm{jmp mProcs[211*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixRotationQuaternion_wrapper(){__asm{jmp mProcs[212*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixRotationX_wrapper(){__asm{jmp mProcs[213*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixRotationY_wrapper(){__asm{jmp mProcs[214*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixRotationYawPitchRoll_wrapper(){__asm{jmp mProcs[215*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixRotationZ_wrapper(){__asm{jmp mProcs[216*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixScaling_wrapper(){__asm{jmp mProcs[217*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixShadow_wrapper(){__asm{jmp mProcs[218*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixTransformation_wrapper(){__asm{jmp mProcs[219*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixTransformation2D_wrapper(){__asm{jmp mProcs[220*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixTranslation_wrapper(){__asm{jmp mProcs[221*4]}}
extern "C" __declspec(naked) void __stdcall D3DXMatrixTranspose_wrapper(){__asm{jmp mProcs[222*4]}}
extern "C" __declspec(naked) void __stdcall D3DXOptimizeFaces_wrapper(){__asm{jmp mProcs[223*4]}}
extern "C" __declspec(naked) void __stdcall D3DXOptimizeVertices_wrapper(){__asm{jmp mProcs[224*4]}}
extern "C" __declspec(naked) void __stdcall D3DXPlaneFromPointNormal_wrapper(){__asm{jmp mProcs[225*4]}}
extern "C" __declspec(naked) void __stdcall D3DXPlaneFromPoints_wrapper(){__asm{jmp mProcs[226*4]}}
extern "C" __declspec(naked) void __stdcall D3DXPlaneIntersectLine_wrapper(){__asm{jmp mProcs[227*4]}}
extern "C" __declspec(naked) void __stdcall D3DXPlaneNormalize_wrapper(){__asm{jmp mProcs[228*4]}}
extern "C" __declspec(naked) void __stdcall D3DXPlaneTransform_wrapper(){__asm{jmp mProcs[229*4]}}
extern "C" __declspec(naked) void __stdcall D3DXPlaneTransformArray_wrapper(){__asm{jmp mProcs[230*4]}}
extern "C" __declspec(naked) void __stdcall D3DXPreprocessShader_wrapper(){__asm{jmp mProcs[231*4]}}
extern "C" __declspec(naked) void __stdcall D3DXPreprocessShaderFromFileA_wrapper(){__asm{jmp mProcs[232*4]}}
extern "C" __declspec(naked) void __stdcall D3DXPreprocessShaderFromFileW_wrapper(){__asm{jmp mProcs[233*4]}}
extern "C" __declspec(naked) void __stdcall D3DXPreprocessShaderFromResourceA_wrapper(){__asm{jmp mProcs[234*4]}}
extern "C" __declspec(naked) void __stdcall D3DXPreprocessShaderFromResourceW_wrapper(){__asm{jmp mProcs[235*4]}}
extern "C" __declspec(naked) void __stdcall D3DXQuaternionBaryCentric_wrapper(){__asm{jmp mProcs[236*4]}}
extern "C" __declspec(naked) void __stdcall D3DXQuaternionExp_wrapper(){__asm{jmp mProcs[237*4]}}
extern "C" __declspec(naked) void __stdcall D3DXQuaternionInverse_wrapper(){__asm{jmp mProcs[238*4]}}
extern "C" __declspec(naked) void __stdcall D3DXQuaternionLn_wrapper(){__asm{jmp mProcs[239*4]}}
extern "C" __declspec(naked) void __stdcall D3DXQuaternionMultiply_wrapper(){__asm{jmp mProcs[240*4]}}
extern "C" __declspec(naked) void __stdcall D3DXQuaternionNormalize_wrapper(){__asm{jmp mProcs[241*4]}}
extern "C" __declspec(naked) void __stdcall D3DXQuaternionRotationAxis_wrapper(){__asm{jmp mProcs[242*4]}}
extern "C" __declspec(naked) void __stdcall D3DXQuaternionRotationMatrix_wrapper(){__asm{jmp mProcs[243*4]}}
extern "C" __declspec(naked) void __stdcall D3DXQuaternionRotationYawPitchRoll_wrapper(){__asm{jmp mProcs[244*4]}}
extern "C" __declspec(naked) void __stdcall D3DXQuaternionSlerp_wrapper(){__asm{jmp mProcs[245*4]}}
extern "C" __declspec(naked) void __stdcall D3DXQuaternionSquad_wrapper(){__asm{jmp mProcs[246*4]}}
extern "C" __declspec(naked) void __stdcall D3DXQuaternionSquadSetup_wrapper(){__asm{jmp mProcs[247*4]}}
extern "C" __declspec(naked) void __stdcall D3DXQuaternionToAxisAngle_wrapper(){__asm{jmp mProcs[248*4]}}
extern "C" __declspec(naked) void __stdcall D3DXRectPatchSize_wrapper(){__asm{jmp mProcs[249*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSHAdd_wrapper(){__asm{jmp mProcs[250*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSHDot_wrapper(){__asm{jmp mProcs[251*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSHEvalConeLight_wrapper(){__asm{jmp mProcs[252*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSHEvalDirection_wrapper(){__asm{jmp mProcs[253*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSHEvalDirectionalLight_wrapper(){__asm{jmp mProcs[254*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSHEvalHemisphereLight_wrapper(){__asm{jmp mProcs[255*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSHEvalSphericalLight_wrapper(){__asm{jmp mProcs[256*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSHMultiply2_wrapper(){__asm{jmp mProcs[257*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSHMultiply3_wrapper(){__asm{jmp mProcs[258*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSHMultiply4_wrapper(){__asm{jmp mProcs[259*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSHMultiply5_wrapper(){__asm{jmp mProcs[260*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSHMultiply6_wrapper(){__asm{jmp mProcs[261*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSHPRTCompSplitMeshSC_wrapper(){__asm{jmp mProcs[262*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSHPRTCompSuperCluster_wrapper(){__asm{jmp mProcs[263*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSHProjectCubeMap_wrapper(){__asm{jmp mProcs[264*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSHRotate_wrapper(){__asm{jmp mProcs[265*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSHRotateZ_wrapper(){__asm{jmp mProcs[266*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSHScale_wrapper(){__asm{jmp mProcs[267*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSaveMeshHierarchyToFileA_wrapper(){__asm{jmp mProcs[268*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSaveMeshHierarchyToFileW_wrapper(){__asm{jmp mProcs[269*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSaveMeshToXA_wrapper(){__asm{jmp mProcs[270*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSaveMeshToXW_wrapper(){__asm{jmp mProcs[271*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSavePRTBufferToFileA_wrapper(){__asm{jmp mProcs[272*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSavePRTBufferToFileW_wrapper(){__asm{jmp mProcs[273*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSavePRTCompBufferToFileA_wrapper(){__asm{jmp mProcs[274*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSavePRTCompBufferToFileW_wrapper(){__asm{jmp mProcs[275*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSaveSurfaceToFileA_wrapper(){__asm{jmp mProcs[276*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSaveSurfaceToFileInMemory_wrapper(){__asm{jmp mProcs[277*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSaveSurfaceToFileW_wrapper(){__asm{jmp mProcs[278*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSaveTextureToFileA_wrapper(){__asm{jmp mProcs[279*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSaveTextureToFileInMemory_wrapper(){__asm{jmp mProcs[280*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSaveTextureToFileW_wrapper(){__asm{jmp mProcs[281*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSaveVolumeToFileA_wrapper(){__asm{jmp mProcs[282*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSaveVolumeToFileInMemory_wrapper(){__asm{jmp mProcs[283*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSaveVolumeToFileW_wrapper(){__asm{jmp mProcs[284*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSimplifyMesh_wrapper(){__asm{jmp mProcs[285*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSphereBoundProbe_wrapper(){__asm{jmp mProcs[286*4]}}
extern "C" __declspec(naked) void __stdcall D3DXSplitMesh_wrapper(){__asm{jmp mProcs[287*4]}}
extern "C" __declspec(naked) void __stdcall D3DXTessellateNPatches_wrapper(){__asm{jmp mProcs[288*4]}}
extern "C" __declspec(naked) void __stdcall D3DXTessellateRectPatch_wrapper(){__asm{jmp mProcs[289*4]}}
extern "C" __declspec(naked) void __stdcall D3DXTessellateTriPatch_wrapper(){__asm{jmp mProcs[290*4]}}
extern "C" __declspec(naked) void __stdcall D3DXTriPatchSize_wrapper(){__asm{jmp mProcs[291*4]}}
extern "C" __declspec(naked) void __stdcall D3DXUVAtlasCreate_wrapper(){__asm{jmp mProcs[292*4]}}
extern "C" __declspec(naked) void __stdcall D3DXUVAtlasPack_wrapper(){__asm{jmp mProcs[293*4]}}
extern "C" __declspec(naked) void __stdcall D3DXUVAtlasPartition_wrapper(){__asm{jmp mProcs[294*4]}}
extern "C" __declspec(naked) void __stdcall D3DXValidMesh_wrapper(){__asm{jmp mProcs[295*4]}}
extern "C" __declspec(naked) void __stdcall D3DXValidPatchMesh_wrapper(){__asm{jmp mProcs[296*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec2BaryCentric_wrapper(){__asm{jmp mProcs[297*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec2CatmullRom_wrapper(){__asm{jmp mProcs[298*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec2Hermite_wrapper(){__asm{jmp mProcs[299*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec2Normalize_wrapper(){__asm{jmp mProcs[300*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec2Transform_wrapper(){__asm{jmp mProcs[301*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec2TransformArray_wrapper(){__asm{jmp mProcs[302*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec2TransformCoord_wrapper(){__asm{jmp mProcs[303*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec2TransformCoordArray_wrapper(){__asm{jmp mProcs[304*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec2TransformNormal_wrapper(){__asm{jmp mProcs[305*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec2TransformNormalArray_wrapper(){__asm{jmp mProcs[306*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec3BaryCentric_wrapper(){__asm{jmp mProcs[307*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec3CatmullRom_wrapper(){__asm{jmp mProcs[308*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec3Hermite_wrapper(){__asm{jmp mProcs[309*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec3Normalize_wrapper(){__asm{jmp mProcs[310*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec3Project_wrapper(){__asm{jmp mProcs[311*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec3ProjectArray_wrapper(){__asm{jmp mProcs[312*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec3Transform_wrapper(){__asm{jmp mProcs[313*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec3TransformArray_wrapper(){__asm{jmp mProcs[314*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec3TransformCoord_wrapper(){__asm{jmp mProcs[315*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec3TransformCoordArray_wrapper(){__asm{jmp mProcs[316*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec3TransformNormal_wrapper(){__asm{jmp mProcs[317*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec3TransformNormalArray_wrapper(){__asm{jmp mProcs[318*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec3Unproject_wrapper(){__asm{jmp mProcs[319*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec3UnprojectArray_wrapper(){__asm{jmp mProcs[320*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec4BaryCentric_wrapper(){__asm{jmp mProcs[321*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec4CatmullRom_wrapper(){__asm{jmp mProcs[322*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec4Cross_wrapper(){__asm{jmp mProcs[323*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec4Hermite_wrapper(){__asm{jmp mProcs[324*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec4Normalize_wrapper(){__asm{jmp mProcs[325*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec4Transform_wrapper(){__asm{jmp mProcs[326*4]}}
extern "C" __declspec(naked) void __stdcall D3DXVec4TransformArray_wrapper(){__asm{jmp mProcs[327*4]}}
extern "C" __declspec(naked) void __stdcall D3DXWeldVertices_wrapper(){__asm{jmp mProcs[328*4]}}

#endif // _SP_WRAP_D3DX9_43_DLL_


#endif // _SP_DS1_FPS_FIX_PLUS_D3DX9_43_H_

